### ISSUE TITLE
Copy button is not working

### ISSUE THREAD

**Issue by Mohab96** [Mohab96/cf-problem-selector-website#1]
When the user generates a problem and tries to copy its code, nothing is copied and the popup that appears upon copying doesn't appear anymore.

**Comment by saransh3** [comment]
Hi @Mohab96 can you please share the video regarding the same issue?

**Comment by Mohab96** [comment]
https://github.com/Mohab96/cf-problem-selector-website/assets/93686102/8778d470-6de5-4193-be4d-1066351e6371
